
server:
  port: 8080
  servlet:
    context-path: /juanng

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_review
    username: postgres
    password: 28122003

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  admin:
    email: ${ADMIN_EMAIL:nguyenluan@admin.com}
    password: ${ADMIN_PASSWORD:nguyenluan123}
